version: '3'
networks:
  healthe:
services:
  brainstorm-auth:
    image: brainstormbub/auth
    networks:
      healthe: null
    ports:
    - 3001
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - PORT=3001
      - HOST=localhost
      - DB_HOST=172.17.2.186
      - DB_PORT=5432
      - DB_NAME=healthe-auth
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DIALECT=postgres
      - GOOGLE_CLIENT_ID=813589990932-ib4krj7urb1pgji160dlnb6npnnmqad0.apps.googleusercontent.com
  api:
    build: ./
    volumes:
    - ./:/var/www/app
    links:
    - brainstorm-auth
    - elasticsearch
    ports:
    - 3000:3000
    networks:
      healthe: null
    depends_on:
    - brainstorm-auth
    - elasticsearch
    environment:
    - NODE_ENV=development
## server Configs
    - HOST=localhost
    - PORT=3000
# api key
    - API_AUTH_KEY=xrwWERbhbc123DCYYwteety
# db Configs
    - DB_HOST=172.17.2.186
    - DB_PORT=5432
    - DB_NAME=healthe-back
    - DB_USERNAME=postgres
    - DB_PASSWORD=postgres
    - DB_DIALECT=postgres
## auth config
    - AUTH_PORT=3001
    - AWS_ACCESS_KEY_ID=AKIAJTZP7DSNYH57VPLA
    - AWS_SECRET_ACCESS_KEY=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
##  MAILER configs
    - SENDGRID_API_KEY =ddd
    - SENDGRID_USER_EMAIL=dd
    - CONSULTATION_EMAIL=ddd
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.3
    networks:
      healthe: null
    ports:
    - 9200:9200
    expose:
    - 9200
    restart: unless-stopped
    volumes:
    - elasticsearch:/usr/share/elasticsearch/data:rw
    environment:
      transport.host: localhost
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
  kibana:
    depends_on:
    - elasticsearch
    image: docker.elastic.co/kibana/kibana-oss:6.4.3
    networks:
      healthe: null
    ports:
    - 5601:5601
    restart: unless-stopped
    environment:
      http.host: 0.0.0.0
      SERVER_NAME: kibana
      ELASTICSEARCH_URL: http://elasticsearch:9200
volumes:
  elasticsearch:
    driver: local