version: '3'

services:
  brainstorm-auth:
    image: brainstormbub/auth
    network-mode: host
    ports:
    - 3001
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - PORT=3001
      - HOST=localhost
      - DB_HOST=172.17.2.186
      - DB_PORT=5432
      - DB_NAME=healthe-auth
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DIALECT=postgres
      - GOOGLE_CLIENT_ID=813589990932-ib4krj7urb1pgji160dlnb6npnnmqad0.apps.googleusercontent.com
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.3
    networks:
      healthe: null
    ports:
    - 9200:9200
    expose:
    - 9200
    restart: unless-stopped
    volumes:
    - elasticsearch:/usr/share/elasticsearch/data:rw
    environment:
      transport.host: localhost
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
  kibana:
    depends_on:
    - elasticsearch
    image: docker.elastic.co/kibana/kibana-oss:6.4.3
    network-mode: host
    ports:
    - 5601:5601
    restart: unless-stopped
    environment:
      http.host: 0.0.0.0
      SERVER_NAME: kibana
      ELASTICSEARCH_URL: http://elasticsearch:9200
volumes:
  elasticsearch:
    driver: bridge
