version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
    ports:
    - 9200:9200
    expose:
    - 9200
    restart: unless-stopped
    volumes:
    - elasticsearch:/usr/share/elasticsearch/data:rw
    environment:
      transport.host: localhost
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"

#  logstash:
#    image: docker.elastic.co/logstash/logstash-oss:7.2.0
#    depends_on:
#    - elasticsearch
#    ports:
#    - 5044:5044
#    restart: unless-stopped
#    volumes:
#    - ./etc/logstash/pipeline:/usr/share/logstash/pipeline:ro

  kibana:
    depends_on:
    - elasticsearch
    image: docker.elastic.co/kibana/kibana-oss:7.2.0
    ports:
    - 5601:5601
    restart: unless-stopped
    environment:
      http.host: 0.0.0.0
      SERVER_NAME: kibana
      ELASTICSEARCH_URL: http://elasticsearch:9200
volumes:
  elasticsearch:
