version: '3'

services:
  brainstorm-auth:
    image: brainstormbub/auth
    network_mode: 'host'
    ports:
    - 3001
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - PORT=3001
      - HOST=localhost
      - DB_HOST=172.17.2.186
      - DB_PORT=5432
      - DB_NAME=healthe-auth
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DIALECT=postgres
      - GOOGLE_CLIENT_ID=813589990932-ib4krj7urb1pgji160dlnb6npnnmqad0.apps.googleusercontent.com
